"""add_url_post_to_event

Revision ID: a6b1779ee633
Revises: 08707a5a9b53
Create Date: 2026-08-13 19:27:21.923204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6b1779ee633'
down_revision: Union[str, Sequence[str], None] = '08707a5a9b53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('poster_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'poster_url')
    # ### end Alembic commands ###
