"""add has_assigned_seats to events

Revision ID: e3d1b5b7120c
Revises: a6b1779ee633
Create Date: 2026-08-14 22:15:59.006109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3d1b5b7120c'
down_revision: Union[str, Sequence[str], None] = 'a6b1779ee633'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('has_assigned_seats', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'has_assigned_seats')
    # ### end Alembic commands ###
